CREATE TABLE projects (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cards (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_id NUMBER REFERENCES projects(id),
  title VARCHAR2(200) NOT NULL,
  description CLOB,
  status VARCHAR2(50),
  position NUMBER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
